# Generated by Django 2.2.4 on 2019-08-26 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areamodel',
            name='frequency_value',
            field=models.IntegerField(blank=True, null=True, verbose_name='운행횟수'),
        ),
    ]
