# Generated by Django 2.2.4 on 2019-08-26 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20190826_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_amount', models.IntegerField(blank=True, null=True, verbose_name='시내버스 대수')),
                ('distance', models.FloatField(blank=True, null=True, verbose_name='거리')),
                ('frequency', models.IntegerField(blank=True, null=True, verbose_name='운행횟수')),
                ('wage', models.IntegerField(blank=True, null=True, verbose_name='요금')),
                ('name', models.ForeignKey(blank=True, max_length=256, null=True, on_delete=django.db.models.deletion.CASCADE, to='analysis.AreaModel', verbose_name='지역명')),
            ],
            options={
                'verbose_name': '지역 기본자료',
                'ordering': ['name'],
            },
        ),
    ]
