# Generated by Django 2.2.4 on 2019-08-26 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_basicfeatures'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drive_Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.CharField(blank=True, max_length=64, null=True, verbose_name='시작 시기')),
                ('text', models.CharField(blank=True, max_length=256, null=True, verbose_name='주요 특징')),
                ('wage', models.IntegerField(blank=True, null=True, verbose_name='요금')),
                ('etc', models.CharField(blank=True, max_length=256, null=True, verbose_name='기타 사항')),
                ('name', models.ForeignKey(blank=True, max_length=256, null=True, on_delete=django.db.models.deletion.CASCADE, to='analysis.AreaModel', verbose_name='지역명')),
            ],
            options={
                'verbose_name': '운영지역',
            },
        ),
    ]
