# Generated by Django 2.2.4 on 2019-08-26 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_drive_area'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basicfeatures',
            options={'verbose_name': '지역 기본자료'},
        ),
    ]
