# Generated by Django 2.2.4 on 2019-08-27 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_auto_20190826_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicfeatures',
            name='outside_people',
            field=models.IntegerField(blank=True, null=True, verbose_name='벽지노선 인구'),
        ),
    ]
