# Generated by Django 2.2.4 on 2019-08-27 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_basicfeatures_outside_people'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicfeatures',
            name='bus_amount',
        ),
        migrations.RemoveField(
            model_name='basicfeatures',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='basicfeatures',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='basicfeatures',
            name='wage',
        ),
    ]
